application: findmeonmap
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /img
  static_dir: static/images  
- url: /css
  static_dir: static/stylesheets  
- url: /.*
  script: main.APP

libraries:
- name: jinja2
  version: latest
